export const entityList = [
	'Game',
	'User',
	'Game Server',
	'Character Type',
	'Character',
	'Asset Type',
	'Asset',
	'Character Asset',
	'Activity Type',
	'Activity',
	'Wallet Category',
	'Wallet',
	'Transaction',
	'Payment',
	'Level',
	'Level Progress',
	'Attribute Group',
	'Character Attribute',
	'Asset Attribute',
];
