export const termOfUseContent = [
	'Welcome to our website. If you continue to browse and use this website, you are agreeing to comply with and be bound by the following terms and conditions of use, which together with our privacy policy govern our relationship with you in relation to this website. If you disagree with any part of these terms and conditions, please do not use our website.',
	"The term 'us' or 'we' refers to the owner of the website. The term 'you' refers to the user or viewer of our website.",
	'The use of this website is subject to the following terms of use:',
	'- The content of the pages of this website is for your general information and use only. It is subject to change without notice.',
	'- Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness, or suitability of the information and materials found or offered on this website for any particular purpose. You acknowledge that such information and materials may contain inaccuracies or errors, and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.',
	'- Your use of any information or materials on this website is entirely at your own risk, for which we shall not be liable. It shall be your responsibility to ensure that any products, services, or information available through this website meet your specific requirements.',
	'- This website contains material that is owned by or licensed to us. This material includes, but is not limited to, the design, layout, look, appearance, and graphics. Reproduction is prohibited other than in accordance with the copyright notice, which forms part of these terms and conditions.',
	'- All trademarks reproduced in this website, which are not the property of, or licensed to the operator, are acknowledged on the website.',
	'- Unauthorised use of this website may give rise to a claim for damages and/or be a criminal offence.',
	'- From time to time, this website may also include links to other websites. These links are provided for your convenience to provide further information. They do not signify that we endorse the website(s). We have no responsibility for the content of the linked website(s).',
	'- Your use of this website and any dispute arising out of such use of the website is subject to the laws of the United States.'
]

export const privacyPolicyContent = [
	'Privacy Policy',
	'Effective date: October 27, 2023',
	'',
	'Our Privacy Policy is designed to help you understand how we collect, use, and safeguard your personal information. By using our services, you consent to the practices described in this Privacy Policy. We may update our Privacy Policy from time to time, so we encourage you to review it periodically for any changes.',
	'',
	'1. Information we collect',
	'We may collect the following types of information:',
	'   - Personal Information: This may include your name, email address, and other identifying information when you sign up or use our services.',
	'   - Usage Information: We may collect information about how you use our services, such as the pages you visit, features you use, and actions you take.',
	'',
	'2. How we use your information',
	'We may use your information for various purposes, including:',
	'   - To provide and maintain our services',
	'   - To improve our services and develop new features',
	'   - To communicate with you, respond to your requests, and send important updates',
	'   - To monitor and analyze usage patterns',
	'',
	'3. Data security',
	'We take data security seriously and implement measures to protect your personal information from unauthorized access, disclosure, alteration, and destruction. However, no method of transmission over the internet or electronic storage is 100% secure, so we cannot guarantee its absolute security.',
	'',
	'4. Your choices',
	'You have the right to access, correct, or delete your personal information. You can also opt out of receiving emails or communications from us. If you have questions or need assistance with your choices, please contact us.',
	'',
	'5. Changes to our Privacy Policy',
	'We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.',
	'',
	'If you have any questions about our Privacy Policy or the use of your information, please contact us.',
]
