name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build_and_deploy:
    permissions: write-all
    runs-on: ubuntu-22.04
    container: node:18-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_DEBUG                            : false
          envkey_BACKEND_ENDPOINT                 : ${{ secrets.BACKEND_ENDPOINT }}
          file_name                               : .env
          fail_on_empty                           : true
      - name: Confirm env file
        run: cat .env
      - name: Install
        run: |
          yarn install --frozen-lockfile --network-timeout 1000000000
      - name: lint
        run: /
          yarn lint
      - name: Build
        run: |
          yarn build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: ghub-fpt
