name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - master
  # pull_request:
  #   branches:
  #     - master
jobs:
  build_and_deploy:
    permissions: write-all
    runs-on: ubuntu-22.04
    container: node:18-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_DEBUG                          : false
          envkey_VITE_FIREBASE_API_KEY          : ${{ secrets.VITE_FIREBASE_API_KEY }}
          envkey_VITE_FIREBASE_PROJECT_ID       : ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          envkey_VITE_FIREBASE_APP_ID           : ${{ secrets.VITE_FIREBASE_APP_ID }}
          envkey_VITE_FIREBASE_AUTH_DOMAIN      : ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          envkey_VITE_PUSHER_APP_KEY            : ${{ secrets.VITE_PUSHER_APP_KEY }}
          envkey_VITE_PUSHER_CLUSTER            : ${{ secrets.VITE_PUSHER_CLUSTER }}
          envkey_VITE_PUSHER_CHANNEL            : ${{ secrets.VITE_PUSHER_CHANNEL }}
          envkey_VITE_PUSHER_BIND_INSERTED_EVENT: ${{ secrets.VITE_PUSHER_BIND_INSERTED_EVENT }}
          envkey_VITE_IDP_URL                   : ${{ secrets.VITE_IDP_URL }}
          envkey_VITE_GMS_URL                   : ${{ secrets.VITE_GMS_URL }}
          envkey_VITE_CLOUDINARY_CLOUDNAME      : ${{ secrets.VITE_CLOUDINARY_CLOUDNAME }}
          envkey_VITE_CLOUDINARY_UPLOADPRESET   : ${{ secrets.VITE_CLOUDINARY_UPLOADPRESET }}
          file_name                       : .env
          fail_on_empty                   : true
      - name: Confirm env file
        run: cat .env
      - name: Install
        run: |
          yarn install --frozen-lockfile --network-timeout 1000000000
      - name: Lint check
        run: |
          yarn lint
      - name: Build
        run: |
          yarn build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: ghub-fpt
